### ISSUE TITLE
template error in "create event

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#168]
In administration on click to create event I get an internal server error (version: docker 2.0.x)

EDIT: same issue when editing an event (=> same template)

EDIT 2: Could not reproduce on current master.

```
Internal Server Error: /manage/new/

TemplateSyntaxError at /manage/new/
Invalid block tag on line 23: 'trans', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?

Request Method: GET
Request URL: https://helfer.stustaculum.de/manage/new/
Django Version: 3.2.6
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.7.3
Python Path: ['/helfertool/src', '.', '', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
Server time: Tue, 24 Aug 2021 20:13:40 +0200
Installed Applications:
('helfertool',
 'modeltranslation',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mozilla_django_oidc',
 'axes',
 'django_bootstrap5',
 'django_icons',
 'django_select2',
 'ckeditor',
 'compressor',
 'registration.apps.RegistrationConfig',
 'statistic.apps.StatisticConfig',
 'badges.apps.BadgesConfig',
 'news.apps.NewsConfig',
 'gifts.apps.GiftsConfig',
 'inventory.apps.InventoryConfig',
 'mail.apps.MailConfig',
 'help.apps.HelpConfig',
 'account.apps.AccountConfig',
 'toolsettings.apps.ToolsettingsConfig',
 'prerequisites.apps.PrerequisitesConfig',
 'toollog.apps.ToollogConfig')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mozilla_django_oidc.middleware.SessionRefresh',
 'axes.middleware.AxesMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]

During handling of the above exception ('trans'), another exception occurred:
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/helfertool/src/registration/views/event.py", line 79, in edit_event
    return render(request, 'registration/admin/edit_event.html', context)
  File "/usr/local/lib/python3.7/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 994, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 973, in render_value_in_context
    value = str(value)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/dist-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/dist-packages/django/forms/boundfield.py", line 97, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/dist-packages/django/forms/widgets.py", line 247, in render
    return self._render(self.template_name, context, renderer)
  File "/usr/local/lib/python3.7/dist-packages/django/forms/widgets.py", line 252, in _render
    return mark_safe(renderer.render(template_name, context))
  File "/usr/local/lib/python3.7/dist-packages/django/forms/renderers.py", line 24, in render
    template = self.get_template(template_name)
  File "/usr/local/lib/python3.7/dist-packages/django/forms/renderers.py", line 30, in get_template
    return self.engine.get_template(template_name)
  File "/usr/local/lib/python3.7/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.7/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.7/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loaders/cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 965, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 965, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),

Exception Type: TemplateSyntaxError at /manage/new/
Exception Value: Invalid block tag on line 23: 'trans', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
Request information:
```

**Comment by LukasSchulz** [comment]
After some hours of looking through the code I think I found the error:
In this file https://github.com/helfertool/helfertool/blob/d750c50440182c750ecd6006307774963b1e08bb/src/helfertool/templates/helfertool/forms/widgets/image_file_input.html#L23 at line 23 (as the error says) the tag "trans" is used (for translation purposes). 

I fixed it for myself by just removing the tag (so instead of `{% trans "Image preview" %}` it's only `"Image preview"`) - I don't really know what the reason is that this is failing, but maybe this helps.

**Comment by svenhertle** [comment]
I think loading the i18n template tags should fix the issue.

I'm a bit confused how this bug came into the release because editing the event is definitely a test case ;) Will looking into that later.

Thanks!

**Comment by svenhertle** [comment]
It was just the missing template tag... Fix is on the `main` branch and new container is building.

Thank you! :)
