### ISSUE TITLE
Missing error handling after failed badge creation

### ISSUE THREAD

**Issue by svenhertle** [helfertool/helfertool#228]
```
TypeError at /.../badges/failed/..../
'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/helfertool/src/registration/decorators/archived.py", line 17, in _decorated
    return function(request, *args, **kwargs)
  File "/helfertool/src/badges/views/generate.py", line 237, in failed
    latex_output = result.info["latex_output"]
```

If `result.info` is None, just show generic error.

**Comment by rsk2** [comment]
Hi @svenhertle, I had a couple of questions regarding this issue.

1. What would be the steps to reproduce this bug?
2. Can you please elaborate on what you mean by generic error?
